---
title: "T11_Wed_reprex Group work"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    runtime: shiny
    source_code: embed
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(flexdashboard)
library(ggplot2)
library(tidyverse)
library(plotly)
library(naniar)
library(kableExtra)
```

```{r}
# read tidy data
fatalcrashes <- read.csv(here::here("data/cleaned_fatalcrashes.csv"))
fatalities <- read.csv(here::here("data/cleaned_fatalities.csv"))
```

```{r}
holidays <- fatalcrashes %>%
  select(State, Year, Month, Christmas.Period, Easter.Period, Time.of.day)
```

Time related crashes {data-icon="fa-adjust"}
==================================

Column {data-width=500} 
-----------------------------------------------------------
### Fatal crashes happens in Christmas period from 2018 to 2020

```{r}
# filter month and check the holidays
monthly <- holidays %>%
  mutate(Month = as.factor(Month)) %>%
  group_by(Month, State)%>%
  count()
```

```{r Christmas, fig.align='center'}
# compare the period of holidays in the last 3 years
period <- holidays %>%
  filter(Year %in% c("2018" : "2020"),
         Month %in% c ("11", "12", "1", "2", "3", "4", "5")) %>%
  mutate(Month = as.factor(Month)) %>%
  group_by(Year, Month, State) %>%
  count() 

period$Month <- factor(period$Month, levels = c("11", "12", "1", "2", "3", "4", "5"))
orderper <- period[order(period$Month),]


# filter Christmas data
Christmas <- orderper %>%
  filter(Month %in% c("11", "12", "1", "2"))

## plot the Christmas change  of recent 6 years
Christmas_fig <- ggplot(Christmas, aes(x = Month, y = n, color = State, group = State))+
  geom_line()+
  geom_point(alpha = 0.8, size = 2)+
  scale_color_brewer(palette = "Set1")+
  theme_classic()+
  facet_wrap(~Year)
ggplotly(Christmas_fig)
```


### Fatal crashes happens in Easter period from 2018 to 2020

```{r Easter, fig.align='center'}
# filter Easter data
Easter <- orderper %>%
  filter(Month %in% c("2", "3", "4", "5"))

## plot the Christmas change  of recent 6 years
Easter_fig <- ggplot(Easter, aes(x = Month, y = n, color = State, group = State))+
  geom_line()+
  geom_point(alpha = 0.8, size = 2)+
  scale_color_brewer(palette = "Set1")+
  theme_classic()+
  facet_wrap(~Year)
ggplotly(Easter_fig)
```





Row
---------------------------------------------------
### Fatal crashes happens by day and night
```{r}
# check the correlation with night and day
night <- holidays %>%
  select(Year, Time.of.day, State) %>%
  mutate(Time.of.day = as.factor(Time.of.day),
         Year = as.factor(Year)) %>%
  group_by(State, Time.of.day, Year) %>%
  count()

# plot the day and night by year
p3 <- ggplot(night, 
       aes(x = n, y = Year, fill = Time.of.day))+
  geom_bar(stat = "identity", position = "fill")+
  facet_wrap(~State, nrow = 1)+
  geom_vline(xintercept = 0.5, color = "yellow")+
  scale_fill_manual(values=c("#ae7181", "#350631"))+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))
  
ggplotly(p3)
```


